using System.Text;

namespace Soap.Services;

/// <summary>
/// Converts a raw browser "Cookie:" header into a Netscape-format cookies.txt
/// file that yt-dlp can read.
/// </summary>
public static class CookieImporter
{
    private const string Domain = ".tiktok.com";

    public record ParseResult(int Count, bool HasSession, List<string> Names);

    /// <summary>
    /// Parses a raw cookie header value (with or without the leading "Cookie:" label).
    /// Returns the cookies it found.
    /// </summary>
    public static ParseResult Parse(string raw)
    {
        var names = new List<string>();
        if (string.IsNullOrWhiteSpace(raw))
            return new ParseResult(0, false, names);

        var text = raw.Trim();
        // Strip "Cookie:" prefix if pasted with it
        if (text.StartsWith("Cookie:", StringComparison.OrdinalIgnoreCase))
            text = text["Cookie:".Length..].Trim();

        bool hasSession = false;
        foreach (var part in text.Split(';'))
        {
            var pair = part.Trim();
            if (pair.Length == 0) continue;

            var eq = pair.IndexOf('=');
            if (eq <= 0) continue;

            var name = pair[..eq].Trim();
            if (name.Length == 0) continue;

            names.Add(name);
            if (name.Equals("sessionid", StringComparison.OrdinalIgnoreCase) ||
                name.Equals("sid_tt", StringComparison.OrdinalIgnoreCase) ||
                name.Equals("sid_guard", StringComparison.OrdinalIgnoreCase))
            {
                hasSession = true;
            }
        }

        return new ParseResult(names.Count, hasSession, names);
    }

    /// <summary>
    /// Builds the Netscape cookies.txt body from a raw cookie header.
    /// Returns null if nothing parsed.
    /// </summary>
    public static string? BuildNetscape(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return null;

        var text = raw.Trim();
        if (text.StartsWith("Cookie:", StringComparison.OrdinalIgnoreCase))
            text = text["Cookie:".Length..].Trim();

        var sb = new StringBuilder();
        sb.AppendLine("# Netscape HTTP Cookie File");
        sb.AppendLine("# Generated by Soap from a pasted Cookie: header");
        sb.AppendLine();

        var expiry = DateTimeOffset.UtcNow.AddYears(10).ToUnixTimeSeconds();
        int written = 0;

        foreach (var part in text.Split(';'))
        {
            var pair = part.Trim();
            if (pair.Length == 0) continue;

            var eq = pair.IndexOf('=');
            if (eq <= 0) continue;

            var name = pair[..eq].Trim();
            var value = pair[(eq + 1)..].Trim();
            if (name.Length == 0) continue;

            // domain  includeSubdomains  path  secure  expiry  name  value
            sb.Append(Domain).Append('\t')
              .Append("TRUE").Append('\t')
              .Append('/').Append('\t')
              .Append("TRUE").Append('\t')
              .Append(expiry).Append('\t')
              .Append(name).Append('\t')
              .Append(value).Append('\n');
            written++;
        }

        return written == 0 ? null : sb.ToString();
    }
}
